version: "3.8"

services:

  selenium-hub:
    image: selenium/hub
    ports:
    - "4444:4444"

  chrome:
    image: selenium/standalone-chrome:3.141.59-20210607
    shm_size: 2gb
    privileged: true
    hostname: chrome
    ports:
      - "4441:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    healthcheck:
      test: curl --fail http://chrome:4444/wd/hub || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  all-tests:
    image: all-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/Python_Test_Automation_Demo
    command:  pytest -sv tests --alluredir=allure-results
    working_dir: /usr/Python_Test_Automation_Demo
    depends_on:
      chrome:
        condition: service_healthy
    networks:
      - default

  report:
      image: all-tests:v1
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/usr/Python_Test_Automation_Demo
      command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
      working_dir: /usr/Python_Test_Automation_Demo
      depends_on:
        - all-tests
      networks:
        - default

networks:
  default:
    driver: bridge