version: "3.8"

services:

  selenium-hub:
    image: selenium/hub
    ports:
    - "4444:4444"

  chrome:
    image: selenium/standalone-chrome:3.141.59-20210607
    shm_size: 2gb
    privileged: true
    hostname: chrome
    ports:
      - "4441:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  all-tests:
    image: all-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/Python_Test_Automation_Demo
    command:  /bin/sh -c "pytest -sv tests/ui_tests/test_block_elements.py --alluredir=allure-results"
    working_dir: /usr/Python_Test_Automation_Demo
    depends_on:
      - chrome
      - selenium-hub
    networks:
      - default

  report:
      image: all-tests:v1
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/usr/Python_Test_Automation_Demo
      command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
      working_dir: /usr/Python_Test_Automation_Demo
      depends_on:
        - all-tests
      networks:
        - default

networks:
  default:
    driver: bridge