name: Build and Publish Docker Images

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run UI test suite
    runs-on: ubuntu-latest

    steps:

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker-compose
        run: docker-compose -f docker-compose.yml up build

      - name: Run docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml ps
          sleep 15

      - name: Run tests
        run: docker-compose -f docker-compose.yml run all-tests

      - name: Shutdown containers
        run: docker-compose -f docker-compose.yml down