name: Build and Publish Docker Images

on:
  label

jobs:
  test:
    name: Run UI test suite
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and run containers
        run: docker-compose -f docker-compose.yml up -d --wait

      - name: Shutdown containers
        run: docker-compose -f docker-compose.yml down