name: Build and Publish Docker Images

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run UI test suite
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker-compose
        run: docker-compose -f docker-compose.yaml build

      - name: Run docker-compose
        run: |
          docker-compose -f docker-compose.yaml up -d
          sleep 15

      - name: Run tests
        run: docker-compose -f docker-compose.yaml run all-tests
        continue-on-error: true

      - name: Shutdown containers
        run: docker-compose -f docker-compose.yaml down

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: "21"
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz && sudo tar -zxvf allure-2.27.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: tests report

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4